name: deploy

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: ./vue

    steps:
      - uses: actions/checkout@v2

      # - name: Cache vue/dist
      #   id: cache-vue-dist
      #   uses: actions/cache@v3
      #   with:
      #     path: vue/dist
      #     key: vue-dist

      - name: use Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.2
      - name: install node modules
        run: cd vue ; npm install
      
      - name: build vue
        run: cd vue ; npm run build

  # deploy:
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Cache vue/dist
  #       id: cache-vue-dist
  #       uses: actions/cache@v3
  #       with:
  #         path: vue/dist
  #         key: vue-dist

      - name: Create ZIP deployment package
        run: git archive HEAD -o deploy_package.zip ; zip -d deploy_package.zip "Procfile"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://lf2-github-action/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name LF2 \
          --source-bundle S3Bucket="lf2-github-action",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --application-name LF2 --environment-name ${{ secrets.EB_ENV }} --version-label "ver-${{ github.sha }}"
        